name: Build Pipeline to Dev New

on:          
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'badges/*'
      - 'pom.xml'
      - '*.svg'
      - '*.json'
      - '*.md'
  workflow_dispatch:
  
env:
  #default is develop
  SOURCECODE_MANAGE_BRANCH: master
  #SOURCECODE_HOME_PATH: api-demo-java11
  #GITLAB_REPO: git.g-able.com/ais-esaving/service-a.git  
  GITOPS_MANAGE_BRANCH: develop
  #GITOPS_APP_NAME: api-demo-java11
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
      - name: "Setup Variable" 
        uses: e-saving/birdtest-template-cicd/Dev/SetupVariableAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitops_token: ${{ secrets.GITOPS_TOKEN }}
          gitops_manage_branch: ${{ env.GITOPS_MANAGE_BRANCH }}
          sourcecode_manage_branch: ${{ env.SOURCECODE_MANAGE_BRANCH }}
          
      - name: "Prepare Configuration" 
        uses: e-saving/birdtest-template-cicd/Dev/PrepareConfigurationAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitops_token: ${{ secrets.GITOPS_TOKEN }}

      - name: "Build and Unit Test" 
        uses: e-saving/birdtest-template-cicd/Dev/BuildTestCodeAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Scan Source Code Quality (SonarQube)" 
        uses: e-saving/birdtest-template-cicd/Dev/CodeQualityScanAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}          
      
      - name: "Build Container" 
        uses: e-saving/birdtest-template-cicd/Dev/BuildContainerAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Update Deployment Configuration" 
        uses: e-saving/birdtest-template-cicd/Dev/UpdateDeploymentConfigAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitops_token: ${{ secrets.GITOPS_TOKEN }}
          
      - name: "Complete Notification" 
        uses: e-saving/birdtest-template-cicd/Dev/NotificationAction@main
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          notify_mesg: "Build Pipeline to Develop Complete with version ${{ env.POM_VERSION }}"
