name: Build Pipeline to Dev New

on:          
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'badges/*'
      - 'pom.xml'
      - '*.svg'
      - '*.json'
      - '*.md'
  workflow_dispatch:
  
env:
  #default is develop
  SOURCECODE_MANAGE_BRANCH: master
  #SOURCECODE_HOME_PATH: api-demo-java11
  #GITLAB_REPO: git.g-able.com/ais-esaving/service-a.git  
  GITOPS_MANAGE_BRANCH: develop
  #GITOPS_APP_NAME: api-demo-java11
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
      - name: "Setup Variable" 
        uses: e-saving/birdtest-template-cicd/Dev/SetupVariableAction@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sourcecode_manage_branch: ${{ env.SOURCECODE_MANAGE_BRANCH }}
          gitops_repo: ${{ secrets.GITOPS_REPO_DEV }}
          gitops_manage_branch: ${{ env.GITOPS_MANAGE_BRANCH }}
          gitops_token: ${{ secrets.GITOPS_TOKEN }}  

